### ISSUE TITLE
[utilities.spacing] Provide a way to alter the generated classes

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#159]
By altering the source code a little bit, we can make the generated classes customizable. So we can get our hipster naming back 😉 :  

```scss
$inuit-spacing-directions: (
  null: null,
  '-top': 't',
  '-right': 'r',
  '-bottom': 'b',
  '-left': 'l',
);

$inuit-spacing-properties: (
  'padding': 'p',
  'margin': 'm'
);

$inuit-spacing-sizes: (
  null: $inuit-global-spacing-unit,
  '--': $inuit-global-spacing-unit-tiny,
  '-': $inuit-global-spacing-unit-small,
  \+: $inuit-global-spacing-unit-large,
  \+\+: $inuit-global-spacing-unit-huge,
  '0': 0
) !default;


@each $property, $property-namespace in $inuit-spacing-properties {

  @each $direction, $direction-namespace in $inuit-spacing-directions {

    @each $size, $value in $inuit-spacing-sizes {

      .u-#{$property-namespace}#{$direction-namespace}#{$size} {
        #{$property}#{$direction}: $value !important;
      }

    }

  }

}
```

*(Updated code example according to [this comment](https://github.com/inuitcss/inuitcss/issues/159#issuecomment-244393085) by  @area73 on September, 16th 2016.)*
