### ISSUE TITLE
font-size() mixin calculation seems weird (to me)

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#163]
Fooling around with the font-size()-mixing, I have a guts feeling that the calculation of the line-height is probably behaving not as intended. Could it be that in this line
```scss
/// font-size() mixin, in 'tools/_tools.font-size.scss', around line 24ff:
// [...]
@if ($line-height == 'auto') {
    line-height: ceil($font-size / $inuit-global-line-height) * ($inuit-global-line-height / $font-size) $important;
}
// [...]
```
an additional set of parenthesis is missing – to extend the block of the ceil-function? 
```scss
// additional parenthesis to extend the block of the ceil-function
@if ($line-height == 'auto') {
    line-height: ceil(($font-size / $inuit-global-line-height) * ($inuit-global-line-height / $font-size)) $important;
}
```
Admittedly, this would always generate 'line-height: 1', so I doubt that this is a solution at all. But I do not understand the results of the regular function, which move up and down from 1.5 to 1 between the various h*-tags in the manner of a sine wave, causing a strange vertical flow... (to my eyes at least).

Also, at the moment, a pixel value is generated, when passing a line-height value to the mixing:
```scss
// somewhere in '_elements.headings.scss'
$inuit-font-size-h1:  32px !default;
h1 {
  @include inuit-font-size($inuit-font-size-h1, $inuit-font-size-h1);
}

/// font-size() mixin, in 'tools/_tools.font-size.scss', around line 30ff:
// [...]
    @if (type-of($line-height) == number or $line-height == 'inherit' or $line-height == 'normal') {
      line-height: $line-height $important;
    }
// [...]

// yields a value of (taken from Chrome DevTools):
h1 {
    line-height: 32px;
}
```

Changing the function to this:
```scss
/// font-size() mixin, in 'tools/_tools.font-size.scss', around line 30ff:
// [...]
@if (type-of($line-height) == number or $line-height == 'inherit' or $line-height == 'normal') {
      line-height: (($line-height / $inuit-global-font-size) * 1rem) $important;
}
// [...]

// yields:
h1 { font-size: 2rem; line-height: 2rem; }
```
would render perfectly fitting rem values.

(I am just 2days old, when it comes to inuitcss. I love it so far, but am most likely misunderstanding lots of things, so please apologize, if my post is useless.)
