### ISSUE TITLE
px2(r)em calculation redundancy?

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#168]
In "_tools.font-size", there is this function around line 20:
```scss
// Calculating px2rem
font-size: ($font-size / $inuit-global-font-size) * 1rem $important;
```

In "_tools.rem", there is a function that returns a rem value:
```scss
@function inuit-rem($value) {
  // [...] - Calculating px2rem
  @return $value / $inuit-global-font-size * 1rem;
}
```
...which is later on used in the mixin "@mixin inuit-rem($property, $value)..." (same file).

Wouldn't it be a step towards more consistency to unify the calculation process and let the first example also use the function?
```scss
// ["_tools.font-size", rewrite of line 20:]
font-size: inuit-rem($font-size) $important;
```

In that case "tools.font-size" must be included after "tools.rem", since it depends on the inuit-rem function. Which rises the question, if functions shouldn't be externalized into a separat file, anyway.

To make "tools.font-size" even more flexible, I could imagine a $unit parameter, like this:
```scss
@mixin inuit-font-size($font-size, $line-height: auto, $important: false, $unit: rem) {
  $u: 1 + $unit;
  // [...]
  font-size: ($font-size / $inuit-global-font-size) * $u $important;
  // [...]
}
```
...or provide an additional "inuit-em()" function and choose the appropriate one via @if @else:
```scss
// [...]
   @if ($unit == rem) {
       font-size: inuit-rem($font-size) $important;
   @else
        font-size: inuit-em($font-size) $important;
// [...]
```

And, for the sake of completeness and because I wonder, what you might think about that: I once stumble over this nice thingy (in a stylus environment, where it is even more convenient; here it is re-written it for scss):
```scss
/// PX2(R)EM multiplier
/// Enables a convenient refactoring px-based layouts. Simply find&replace all px with *$pxr.
/// @example scss - How to use $pxr / $pre
/// body { font-size: 24*$pxe; padding-left: 12*$pxe }
/// A variable that initiates a math operation to render rem or em.
/// Needs the $base-font-size *without* a unit!
$inuit-global-font-size--no-unit: $inuit-global-font-size / (($inuit-global-font-size * 0) + 1);
$pxr: (1 / $inuit-global-font-size--no-unit) * 1rem;
$pxe: (1 / $inuit-global-font-size--no-unit) * 1em; 
```

To me, this is extremely useful, because it is very short. Don't know, though, if that would be of any help here...

**Comment by csshugs** [comment]
> Wouldn't it be a step towards more consistency to unify the calculation process and let the first example also use the function?

Absolutely!

> In that case "tools.font-size" must be included after "tools.rem", since it depends on the inuit-rem function. 

That's a problem.

I ask myself, if we need `inuit-rem` (the function and the mixin) at all? At the moment we just use it in [`_example.components.buttons.scss`](https://github.com/inuitcss/inuitcss/blob/6e4095b86224747c4cac775d2757eb61c893f85e/components/_example.components.buttons.scss#L100-L106) and in [`_generic.shared.scss`](https://github.com/inuitcss/inuitcss/blob/develop/generic/_generic.shared.scss#L24-L33).
The button component is just an example file so we could just use `px` there. In `_generic.shared` we could write it just as in `_tools.font-size`:

```scss
address,
h1, h2, h3, h4, h5, h6,
blockquote, p, pre,
dl, ol, ul,
figure,
hr,
table,
fieldset {
  margin-bottom: ($inuit-global-spacing-unit / $inuit-global-font-size) * 1rem;
}

dd, ol, ul {
  margin-left: ($inuit-global-spacing-unit / $inuit-global-font-size) * 1rem;
}
```

I think inuitcss doesn't need to provide such a mixin. When people want to use `rem` in their project, their could make up such a function/mixin themselves.  

*#inuitcssplugin*
