### ISSUE TITLE
Responsive show/hide

### ISSUE THREAD

**Issue by tymondesigns** [inuitcss/inuitcss#175]
Hey chaps...

Judging by the discussion in #63 it seems that there was an intention of adding responsive classes to `_utilities.hide.scss`.

I see it going something like this

```scss
@if (variable-exists(mq-breakpoints)) {

  @each $inuit-bp-name, $inuit-bp-value in $mq-breakpoints {

    @include mq($from: $inuit-bp-name) {

      .u-hidden\@#{$inuit-bp-name} { display: none !important; }
      .u-shown\@#{$inuit-bp-name}  { display: inherit !important; }

    }

  }

}

```

Although this does raise the question again of [naming the file](https://github.com/inuitcss/inuitcss/issues/63#issuecomment-229939259).

Anyways, I think it's worth another look, because these classes are pretty damn useful imo

**Comment by herzinger** [comment]
Yes, they really are. I always end up adding something like that in my projects.

**Comment by herzinger** [comment]
I tried your approach, but had some trouble with the display: inherit rule. Sometimes I need to control exactly what display type I want for the revealed element, independently of it's parent. It's not a pretty solution, so I'm all for inputs:

```sass
@if (variable-exists(mq-breakpoints)) {

  @each $inuit-bp-name, $inuit-bp-value in $mq-breakpoints {

    @include mq($from: $inuit-bp-name) {

      .u-hidden\@#{$inuit-bp-name} { display: none !important; }
      .u-shown\@#{$inuit-bp-name}  { display: inherit !important; }
      
      .u-display-block.u-shown\@#{$inuit-bp-name}  { 
        display: block !important;
      }

      .u-display-inline-block.u-shown\@#{$inuit-bp-name}  { 
        display: inline-block !important;
      }

      .u-display-inline.u-shown\@#{$inuit-bp-name}  { 
        display: inline !important;
      }

    }

  }

}
```

**Comment by nenadjelovac** [comment]
@tymondesigns @herzinger figuring out "default" display mode of an element is hard. That's why I take the mobile first css approach. What that means (in an example) is this:

```html
<div class="u-hidden@md u-hidden@xlg">
```

This would hide the div on medium and extralarge viewports. In a large number of projects I can get away with this approach. However, there are times where I need to hide something on small viewports (or maybe a few more). For that project I add `@sm` breakpoint <sup>[1]</sup> . 
In that case I can do something like:

```html
<div class="u-hidden@sm u-hidden@md u-hidden@xlg">
```

Which would show the div only on large (`@lg`) viewports in its default display mode (`block`, `inline`, or `inline-block` - in my approach I don't (have to) care). Yes, it does add a little bit more classes in the markup, but I think it is readable and it keeps my (s)css clean. Win win IMO :-)

---

1) In that case you have to add `$until` (aka `max-width`) breakpoint for `@sm`. Something like @moog16 suggested [here](https://github.com/inuitcss/inuitcss/issues/160#issue-176476723).

**Comment by csshugs** [comment]
@herzinger 

> Sometimes I need to control exactly what display type I want for the revealed element, independently of it's parent.

That's why I'd vote for not integrating such a module. Although I find this approach very useful myself, it quickly becomes way too specific to be a part of inuitcss.

This is easy to implement by themselves, though, so it could probably a inuitcss plugin provided by anyone who's interested in opening a dedicated repo.

**Comment by csshugs** [comment]
Is everyone of @inuitcss/core d'accord, that we will not add responsive hide/show classes at the moment?

**Comment by florianbouvot** [comment]
@csshugs  Sorry for the late, but I agree.

**Comment by hayatbiralem** [comment]
Hi,

I think we could try a more convenient way and we can disable by default.

Why not a mobile-first? I was inspired by `_utilities.inuit-widths`.

### _utilities.display.scss

```scss

$inuit-displays: true;
$inuit-display-aliases: true;

/* ==========================================================================
   #DISPLAY
   ========================================================================== */

/**
 * Responsive display helpers.
 */

// Optionally, inuitcss can generate display helper classes. E.g.:
//
//   .u-display-block
//   .u-display-inline-block
//   .u-display-none

$inuit-displays: false !default;
$inuit-display-values: (
        none,
        inline,
        inline-block,
        block
) !default;


// Optionally, inuitcss can generate display helper aliases. E.g.:
//
//   .u-show
//   .u-hide@tablet
//   .u-hide
//   .u-show@tablet

$inuit-display-aliases: false !default;
$inuit-display-alias-definitions: (
        none: hide,
        block: show
) !default;


// A mixin to spit out our display classes.
//
//   .u-display-none@tablet

@mixin inuit-displays($display-values, $breakpoint: null) {

  // Loop through the responsive display values.
  @each $display-value in $display-values {

    // Make a rule in the format `.u-display-block[@<breakpoint>]`.
    $rule: '.u-display-#{$display-value}#{$breakpoint}';

    // Add alias to rule if exists.
    $alias: map-get($inuit-display-alias-definitions, $display-value);
    @if $inuit-display-aliases == true and $alias != null {
      $rule: $rule + ", .u-#{$alias}#{$breakpoint}";
    }

    // Build it.
    #{$rule} {
      display: $display-value !important;
    }
  }

}


// check if enabled
@if $inuit-displays == true {

  // global helpers
  @include inuit-displays($inuit-display-values);

  // responsive helpers
  @if (variable-exists(mq-breakpoints)) {
    @each $inuit-bp-name, $inuit-bp-value in $mq-breakpoints {
      @include mq($from: $inuit-bp-name) {
        @include inuit-displays($inuit-display-values, \@#{$inuit-bp-name});
      }
    }
  }

}
```

### output

```css
.u-display-none, .u-hide {
  display: none !important;
}

.u-display-inline {
  display: inline !important;
}

.u-display-inline-block {
  display: inline-block !important;
}

.u-display-block, .u-show {
  display: block !important;
}

@media (min-width: 20em) {
  .u-display-none\@mobile, .u-hide\@mobile {
    display: none !important;
  }
  .u-display-inline\@mobile {
    display: inline !important;
  }
  .u-display-inline-block\@mobile {
    display: inline-block !important;
  }
  .u-display-block\@mobile, .u-show\@mobile {
    display: block !important;
  }
}

@media (min-width: 46.25em) {
  .u-display-none\@tablet, .u-hide\@tablet {
    display: none !important;
  }
  .u-display-inline\@tablet {
    display: inline !important;
  }
  .u-display-inline-block\@tablet {
    display: inline-block !important;
  }
  .u-display-block\@tablet, .u-show\@tablet {
    display: block !important;
  }
}

@media (min-width: 61.25em) {
  .u-display-none\@desktop, .u-hide\@desktop {
    display: none !important;
  }
  .u-display-inline\@desktop {
    display: inline !important;
  }
  .u-display-inline-block\@desktop {
    display: inline-block !important;
  }
  .u-display-block\@desktop, .u-show\@desktop {
    display: block !important;
  }
}

@media (min-width: 81.25em) {
  .u-display-none\@wide, .u-hide\@wide {
    display: none !important;
  }
  .u-display-inline\@wide {
    display: inline !important;
  }
  .u-display-inline-block\@wide {
    display: inline-block !important;
  }
  .u-display-block\@wide, .u-show\@wide {
    display: block !important;
  }
}
```

Users can use other display values like `table`, `table-cell`, etc. with optional aliases if they want or they just use `none` and `block`.

What are you saying? Is not that useful?

**Comment by lhermann** [comment]
I know this one is closed, but for the record I want to post my responsive hide utility which I add in every project, called ```_utilities.responsive-hide.scss```.

The ```@from-``` and ```@until-``` prefixes are not inuit-conform, but very useful I find.

```scss
/* ==========================================================================
   #RESPONSIVE HIDE
   ========================================================================== */

/**
 * Example usage:
 * <div class="u-hidden@from-tablet">
 * <div class="u-hidden@until-tablet">
 */

$breakpoint-separator: \@;

@each $bp-name, $bp-value in $mq-breakpoints {

    .u-hidden#{$breakpoint-separator}from-#{$bp-name}{
        @include mq($from: $bp-name) {
            display: none !important;
        }
    }

    .u-hidden#{$breakpoint-separator}until-#{$bp-name}{
        @include mq($until: $bp-name) {
            display: none !important;
        }
    }

}
```

Hope it helps someone.
