### ISSUE TITLE
[utilities.widths] sometimes we need offset class like u-offset-1/5.

### ISSUE THREAD

**Issue by hayatbiralem** [inuitcss/inuitcss#180]
Hi,

I added this feature to my current project because I need it. Maybe others are interested.

Code looks like this:

````scss
// Build a class in the format `.u-offset-1/5[@<breakpoint>]`.
.u-offset-#{$numerator}\/#{$denominator}#{$breakpoint} {
  margin-left: ($numerator / $denominator) * 100% !important;
}
```

What do you think?
It can be added to the core?
