### ISSUE TITLE
New optional utility: display

### ISSUE THREAD

**Issue by hayatbiralem** [inuitcss/inuitcss#190]
Hi,

This issue has already been discussed on #175 but I think this is a different approach.

I think we could try a more convenient way and we can disable it by default.

Why not a mobile-first? I was inspired by `_utilities.widths`.

### _utilities.displays.scss

```scss

// Enable inuit-displays.

$inuit-displays: true;
$inuit-display-aliases: true;


/* ==========================================================================
   #DISPLAYS
   ========================================================================== */

/**
 * Responsive display helpers.
 */


// Optionally, inuitcss can generate display helper classes. E.g.:
//
//   .u-display-block
//   .u-display-inline-block
//   .u-display-none

$inuit-displays: false !default;
$inuit-display-values: (
        none,
        inline,
        inline-block,
        block
) !default;


// Optionally, inuitcss can generate display helper aliases. E.g.:
//
//   .u-show
//   .u-hide@tablet
//   .u-hide
//   .u-show@tablet

$inuit-display-aliases: false !default;
$inuit-display-alias-definitions: (
        none: hide,
        block: show
) !default;


// A mixin to spit out our display classes.
//
//   .u-display-none@tablet

@mixin inuit-displays($display-values, $breakpoint: null) {

  // Loop through the display values.
  @each $display-value in $display-values {

    // Make a rule in the format `.u-display-block[@<breakpoint>]`.
    $rule: '.u-display-#{$display-value}#{$breakpoint}';

    // Add alias to rule if exists.
    $alias: map-get($inuit-display-alias-definitions, $display-value);
    @if $inuit-display-aliases == true and $alias != null {
      $rule: $rule + ", .u-#{$alias}#{$breakpoint}";
    }

    // Build it.
    #{$rule} {
      display: $display-value !important;
    }
  }

}


// Check if enabled.
@if $inuit-displays == true {

  // Global helpers.
  @include inuit-displays($inuit-display-values);

  // Responsive helpers.
  @if (variable-exists(mq-breakpoints)) {
    @each $inuit-bp-name, $inuit-bp-value in $mq-breakpoints {
      @include mq($from: $inuit-bp-name) {
        @include inuit-displays($inuit-display-values, \@#{$inuit-bp-name});
      }
    }
  }

}
```

### output

```css
.u-display-none, .u-hide {
  display: none !important;
}

.u-display-inline {
  display: inline !important;
}

.u-display-inline-block {
  display: inline-block !important;
}

.u-display-block, .u-show {
  display: block !important;
}

@media (min-width: 20em) {
  .u-display-none\@mobile, .u-hide\@mobile {
    display: none !important;
  }
  .u-display-inline\@mobile {
    display: inline !important;
  }
  .u-display-inline-block\@mobile {
    display: inline-block !important;
  }
  .u-display-block\@mobile, .u-show\@mobile {
    display: block !important;
  }
}

@media (min-width: 46.25em) {
  .u-display-none\@tablet, .u-hide\@tablet {
    display: none !important;
  }
  .u-display-inline\@tablet {
    display: inline !important;
  }
  .u-display-inline-block\@tablet {
    display: inline-block !important;
  }
  .u-display-block\@tablet, .u-show\@tablet {
    display: block !important;
  }
}

@media (min-width: 61.25em) {
  .u-display-none\@desktop, .u-hide\@desktop {
    display: none !important;
  }
  .u-display-inline\@desktop {
    display: inline !important;
  }
  .u-display-inline-block\@desktop {
    display: inline-block !important;
  }
  .u-display-block\@desktop, .u-show\@desktop {
    display: block !important;
  }
}

@media (min-width: 81.25em) {
  .u-display-none\@wide, .u-hide\@wide {
    display: none !important;
  }
  .u-display-inline\@wide {
    display: inline !important;
  }
  .u-display-inline-block\@wide {
    display: inline-block !important;
  }
  .u-display-block\@wide, .u-show\@wide {
    display: block !important;
  }
}
```

Users can use other display values like `table`, `table-cell`, etc. with optional aliases if they want or they just use `none` and `block`.

What are you saying? Is not that useful?
