### ISSUE TITLE
What is the right place of `scopes` in the main.scss?

### ISSUE THREAD

**Issue by hayatbiralem** [inuitcss/inuitcss#196]
Hi,

I want to use `scopes/scopes.cms-content.scss` in my current project. What position do you think a more accurate? After `generic` styles or other?

Thanks.

**Comment by csshugs** [comment]
Can you elaborate, what exactly you want to achieve with that scope? You want to modify a component depending on which scope it is in?

**Comment by hayatbiralem** [comment]
No, I just want to style the simple tags like `ul`, `ol`, etc. from the cms.

**Comment by csshugs** [comment]
@hayatbiralem 
I don't know if I get you right. When you just want to style base elements like `ul` etc. it would go into the elements layer, which would be `elements/_elements.lists.scss` for example. So this file could look like this:

```scss
ul {
  margin-left: 0;
  list-style-type: square;
}
```

When you want to style this base element differently, when it's in a specific scope (e.g. when it is in the RTE of a CMS), you would write this variation right into the same file: 


```scss
ul {
  margin-left: 0;
  list-style-type: square;

  .s-rte & {
    list-style-type: disc;
  }

}
```

Is this what you're after?
