### ISSUE TITLE
[tools.rem] Remove rem-function?

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#204]
As mentioned [several times](https://github.com/inuitcss/inuitcss/pull/118#issuecomment-237561813) [before](https://github.com/inuitcss/inuitcss/issues/168#issuecomment-250723522), I'm in favor of removing the `inuit-rem` function and mixin, i.e. the whole partial.

I'm not saying, that this is useless in general. Quite the contrary. But we don't consider inuitcss as a mixin library and will not provide a whole lot of functionality which we don't need in the first place for the framework itself. And since this is just used in the [`_example.components.buttons.scss`](https://github.com/inuitcss/inuitcss/blob/126bebe2ff2146b7101ef28fb1b2c0c4832261dc/components/_example.components.buttons.scss#L100-L106) and in [`_generic.shared.scss`](https://github.com/inuitcss/inuitcss/blob/develop/generic/_generic.shared.scss#L24-L33), IMO we can dump it:

``` scss
// _example.components.buttons.scss

.c-btn--small {
  padding: $inuit-global-spacing-unit-tiny $inuit-global-spacing-unit-small;
}

.c-btn--large {
  padding: $inuit-global-spacing-unit $inuit-global-spacing-unit-large;
}
```

``` scss
// _generic.shared.scss


address,
h1, h2, h3, h4, h5, h6,
blockquote, p, pre,
dl, ol, ul,
figure,
hr,
table,
fieldset {
  margin-bottom: $inuit-global-spacing-unit;
}


/**
 * Consistent indentation for lists.
 */

dd, ol, ul {
  margin-left: $inuit-global-spacing-unit;
}
```

The way it is used in the [buttons](https://github.com/inuitcss/inuitcss/blob/126bebe2ff2146b7101ef28fb1b2c0c4832261dc/components/_example.components.buttons.scss#L100-L106) component, it's not IE8 compatible, because it just outputs a `rem` value without `px` fallback. I know, it's just an example file, but as a matter of fact, in that specific case, you could not use the `inuit-rem` mixin like this:

``` scss
.c-btn--small {
  @include inuit-rem(padding, $inuit-global-spacing-unit-tiny $inuit-global-spacing-unit-small);
}
```

because the mixin accepts no shorthand declarations, i.e. in this case we would have to write:

``` scss
.c-btn--small {
  @include inuit-rem(padding-top, $inuit-global-spacing-unit-tiny);
  @include inuit-rem(padding-bottom, $inuit-global-spacing-unit-tiny);
  @include inuit-rem(padding-left, $inuit-global-spacing-unit-small);
  @include inuit-rem(padding-right, $inuit-global-spacing-unit-small);
}
```

which makes the mixin kind of obsolete in those cases and you have to go back to the `inuit-rem` function in those circumstances.

Apart from that, I wonder why we use `rem` units at all in `generic.shared`? Because in [all](https://github.com/inuitcss/inuitcss/blob/126bebe2ff2146b7101ef28fb1b2c0c4832261dc/objects/_objects.block.scss#L17) [other](https://github.com/inuitcss/inuitcss/blob/develop/objects/_objects.media.scss#L18) [modules](https://github.com/inuitcss/inuitcss/blob/develop/objects/_objects.wrapper.scss#L19-L20) where `margin`s are assigned, we are just declaring `px` values. I don't see why in this instance there need to be `rem` values.
