### ISSUE TITLE
[objects.pack] Default vertical alignment definition is missing

### ISSUE THREAD

**Issue by hayatbiralem** [inuitcss/inuitcss#220]
Hi,

I noticed just now default vertical alignment definition is missing so items aligning to [baseline](http://www.w3schools.com/cssref/pr_pos_vertical-align.asp).

I think we have two choices:

### Choice 1

We can define default alignment to `top`.

```scss
/**
 * 1. Cause children to adopt table-like structure.
 * 2. Default vertical alignment.
 */
.o-pack__item {
  display: table-cell; /* [1] */
  vertical-align: top; /* [2] */

  /* Vertical alignment variants.
     ====================================================================== */

  .o-pack--middle > & {
    vertical-align: middle;
  }

  .o-pack--bottom > & {
    vertical-align: bottom;
  }

}
```

### Choice 2

.. or we can keep default baseline alignment and define new modifier for `top`.

```scss
/**
 * 1. Cause children to adopt table-like structure.
 */
.o-pack__item {
  display: table-cell; /* [1] */

  /* Vertical alignment variants.
     ====================================================================== */

  .o-pack--top > & {
    vertical-align: top;
  }

  .o-pack--middle > & {
    vertical-align: middle;
  }

  .o-pack--bottom > & {
    vertical-align: bottom;
  }

}
```

What do you think about this?
