### ISSUE TITLE
List based objects overlap

### ISSUE THREAD

**Issue by herzinger** [inuitcss/inuitcss#242]
After removing the `.o-list-inline--delimited` modifier, take a look at that:

**list-bare object**:
```scss
.o-list-bare {
  list-style: none;
  margin-left: 0;
}
```

**list-inline object**:
```scss
.o-list-inline {
  margin-left: 0;
  list-style: none;
}

  .o-list-inline__item {
    display: inline-block;
  }
```

That being the case, I suggest we make the list-inline object a modifier of the list-bare object, like so:

```scss 
.o-list-bare {
  margin-left: 0;
  list-style: none;
}

  .o-list-bare--inline {

    .o-list-bare__item {
      display: inline-block;
    }
    
  }
```
