### ISSUE TITLE
Shouldn't objects.list-bare also affect <dl>?

### ISSUE THREAD

**Issue by hatzipanis** [inuitcss/inuitcss#280]
...given that it's purpose is to strip indentation from lists?

**Comment by csshugs** [comment]
@hatzipanis Well, that seems like a reasonable idea.

We could enhance our list-bare object like this, then:

```scss
.o-list-bare {
  list-style: none;
  margin-left: 0;
    
  dd {
    margin-left: 0;
  }
    
}
```

What does @inuitcss/core think?

**Comment by hatzipanis** [comment]
Good to hear! Just something I find myself having to do it each project.

Perhaps we target it a bit more specifically?

```scss
.o-list-bare {
  list-style: none;
  margin-left: 0;
    
  > dd {
    margin-left: 0;
  }
}
```
