### ISSUE TITLE
[generic.normalize] Update to v6.0.0

### ISSUE THREAD

**Issue by KingScooty** [inuitcss/inuitcss#288]
Form elements in `inuitcss` appear to be inheriting some fugly opinionated code from `normalize@5.0.0`. 

The culprit is this:

```css
/**
 * 1. Change the font styles in all browsers (opinionated).
 * 2. Remove the margin in Firefox and Safari.
 */

button,
input,
optgroup,
select,
textarea {
  font-family: sans-serif; /* 1 */
  font-size: 100%; /* 1 */
  line-height: 1.15; /* 1 */
  margin: 0; /* 2 */
}
```

Which does not get picked up when we override the `line-height` via `html {}` in inuit. This results in form elements having completely different vertical rhythm and heights to all other elements.

It's fugly.

It's since been removed in `6.0.0` so i highly recommend we upgrade. I've already done the change, but i'm opening this issue first as per contribution requirements.
