### ISSUE TITLE
Responsive headers

### ISSUE THREAD

**Issue by solleer** [inuitcss/inuitcss#290]
Is there a way for there to be responsive headers so that at a certain breakpoint the font size increases? I am mainly asking so that it can tie in with the header utilities too.

**Comment by herzinger** [comment]
If you want responsive font sizes for headers, you can:

1. not use utilities, just write your own objects or even directly alter the elements level (if consistent enough);
2. extend them with custom media-querie rules.

Either way it's too specific and unusual - and I argue wrong in most cases, from a design standpoint - to be part of the framework in itself.

**Comment by edtorba** [comment]
What if you would have something like this? Basically allows to set min and max font size and scales in between those two breakpoints.
```scss
///
/// Viewport sized typography with minimum and maximum values
///
/// @author Eduardo Boucas (@eduardoboucas)
///
/// @param {Number}   $responsive  - Viewport-based size
/// @param {Number}   $min         - Minimum font size (px)
/// @param {Number}   $max         - Maximum font size (px)
///                                  (optional)
/// @param {Number}   $fallback    - Fallback for viewport-
///                                  based units (optional)
///
/// @example scss - 5vw font size (with 50px fallback), 
///                 minumum of 35px and maximum of 150px
///  @include responsive-font(5vw, 35px, 150px, 50px);
///
@mixin responsive-font($responsive, $min, $max: false, $fallback: false) {
  $responsive-unitless: $responsive / ($responsive - $responsive + 1);
  $dimension: if(unit($responsive) == 'vh', 'height', 'width');
  $min-breakpoint: $min / $responsive-unitless * 100;
  
  @media (max-#{$dimension}: #{$min-breakpoint}) {
    font-size: $min;
  }
  
  @if $max {
    $max-breakpoint: $max / $responsive-unitless * 100;
    
    @media (min-#{$dimension}: #{$max-breakpoint}) {
      font-size: $max;
    }
  }
  
  @if $fallback {
    font-size: $fallback;
  }
  
  font-size: $responsive;
}
```
Source:
https://css-tricks.com/snippets/sass/viewport-sized-typography-minimum-maximum-sizes/
