### ISSUE TITLE
how to reset pull "u-pull-1/3@mobile" at desktop width ?

### ISSUE THREAD

**Issue by codemonkeynorth** [inuitcss/inuitcss#316]
Hi,

I'm trying to do a pull on mobile, and then remove that on desktop

I thought 0/3 might do it, but it doesn't seem to work
`u-pull-1/3@mobile u-pull-0/3@desktop u-1/3`

thanks for any advice... I'm not sure it's built in at the moment, unless I've missed something.
ie something like `u-pull-none@` , `u-pull-reset@` etc would be useful

this works for specific >0 push/pull amount, so i know it's not my setup
`u-pull-1/3@mobile u-push-1/3@desktop u-1/3`

thanks
J

**Comment by herzinger** [comment]
Good point... I never use pull/push, so it's the first time I think about it, but we don't have anything of the sort. The pull/push utilities are generated based on the same code we use for the width utilities, and there's no 0 width. This is something we should include. For now, here is a quick and dirty fix (untested, but should do the trick):

```scss
@if (variable-exists(mq-breakpoints)) {

  @each $inuit-bp-name, $inuit-bp-value in $mq-breakpoints {

    @include mq($from: $inuit-bp-name) {
      
      @if ($inuit-offsets == true) {

        .u-push-reset#{$breakpoint} {
          left: auto !important;
        }

        .u-pull-reset#{$breakpoint} {
          right: auto !important;
        }

      }

    }

  }

}
```

Thanks for the feedback
