### ISSUE TITLE
No support for 'u-[prop]@[vp]-down' and 'u-[prop]@[vp]-only' spacing utility classes

### ISSUE THREAD

**Issue by simonpay** [inuitcss/inuitcss#326]
Using the new [inuit v6 _utilities.responsive-spacings.scss](https://github.com/inuitcss/inuitcss/blob/6.0.0-beta.5/utilities/_utilities.responsive-spacings.scss) (that uses sass-mq), there doesn't appear to be a way to generate _down_ and _only_ responsive utility classes. 

E.g:
- `u-margin-bottom@medium-down` - applies to the medium viewport and DOWN.
- `u-margin-bottom@medium-only` - applies to the medium viewport ONLY.

With [inuit v5 trumps.spacing-responsive ](https://github.com/inuitcss/trumps.spacing-responsive/blob/master/_trumps.spacing-responsive.scss), using the `$breakpoints` map below...

````sass
$breakpoints: (
    "medium-up"     "only screen and (min-width: 40.0625em)",
    "medium-down"   "only screen and (max-width: 64.0525em)",
    "medium-only"   "only screen and (min-width: 40.0625em) and (max-width: 64.0525em)",
);
````
...we could generate the classes `u-medium-up-mb`,  `u-medium-down-mb` and `u-medium-only-mb`:

````css
@media only screen and (min-width: 40.0625em) {
    .u-medium-up-mb
        margin-bottom: 1.5rem !important;
    }
}

@media only screen and (max-width: 64.0525em) {
    .u-medium-down-mb {
        margin-bottom: 1.5rem !important;
    }
}

@media only screen and (min-width: 40.0625em) and (max-width: 64.0525em) {
    .u-medium-only-mb {
        margin-bottom: 1.5rem !important;
    }
}
````

I'm about to upgrade from inuit 5 to 6, but I use the _down_ and _only_ classes frequently, so need a way to generate them.

Do you have a way to generate them or do you recommend not using this type of class? 

If I use a _mobile-first_ cascade approach, I could achieve the result I want, but I would have to 'reset' the spacing on the next viewport, which would involve adding additional classes that I never needed before. 

For example, assume I wanted to add `margin-bottom` to an element ONLY in the _medium_ viewport. 

I could add the `u-margin-bottom@medium` class and then reset it for the large viewport using `u-margin-bottom-0@large`. 

````
<div class="u-margin-bottom@medium u-margin-bottom-0@large"></div>
````

However, this not only adds another class in the markup, but also creates a hard `margin-bottom: 0 !important` that will be applied to all larger viewports, which may cause specificity issues with other CSS targeting the same element.

I would much rather continue writing this:

````
<div class="u-margin-bottom@medium-only"></div>
````

The _down_ and _only_ responsive utility classes have been working well for me, is there a reason why inuit 6 doesn't support them anymore?
