### ISSUE TITLE
Extending inuitcss to my project's needs - how to approach

### ISSUE THREAD

**Issue by apsuhos** [inuitcss/inuitcss#332]
This is the default o-wrapper object
```css
.o-wrapper {
  @include inuit-clearfix();
  padding-right: $inuit-global-spacing-unit;
  padding-left:  $inuit-global-spacing-unit;
  margin-right: auto;
  margin-left:  auto;
  max-width: $inuit-wrapper-width;
}
```
I want to have the paddings changed as the media queries kick in:

```css
.o-wrapper {
	@include mq($from: mobile) {
		padding-right: $inuit-global-spacing-unit-small;
		padding-left:  $inuit-global-spacing-unit-small;
	}
	@include mq($from: tablet) {
		padding-right: $inuit-global-spacing-unit;
		padding-left:  $inuit-global-spacing-unit;
	}
	@include mq($from: desktop) {
		padding-right: $inuit-global-spacing-unit-large;
		padding-left:  $inuit-global-spacing-unit-large;
	}
	@include mq($from: wide) {
		padding-right: $inuit-global-spacing-unit-huge;
		padding-left:  $inuit-global-spacing-unit-huge;
	}
}
```
My question is where to insert these lines of code? My first thought was to insert it in my main.scss file like this:

```css
// OBJECTS
//
// Uncomment and add to this section as necessary.
@import "inuitcss/objects/objects.wrapper";
@import "objects/objects.projects-wrapper"
....
etc
```
Then I decided it would be better if I created an new component:

```css
// COMPONENTS
//
// Build and include your project’s UI Compoments here.
// @import "inuitcss/components/example.components.buttons";
@import "components/components.projects-wrapper"
```
and call it like this:
```html
<div class="o-wrapper c-wrapper">
	<h1>Hello world</h1>
</div>
```

Which is the prefered approach? Is there one that I haven't thought of? I tend to feel that it should be considered as a component but I am still trying to grasp this whole idea behind inuitcss and I do not want to be wrong.
