### ISSUE TITLE
Working with objects & components

### ISSUE THREAD

**Issue by apsuhos** [inuitcss/inuitcss#334]
Hey,

I have a follow up question after the [#332](https://github.com/inuitcss/inuitcss/issues/332) issue I opened the other day and I would really like a clarification because I have reached a milestone with inuitcss and I truly believe that this will make me grasp the whole concept correctly.

Based on my reading about components I have reached to the conclusion that they are described by the following principles:
1. Extremely focused
1. Shouldn't have any dependencies (where in the UI)
1. Should be designed to stand-alone
1. Enclose specific semantics and styling

Let's say I want to create the following component:

![c-ingredients](https://user-images.githubusercontent.com/2563197/33794244-a458f92c-dcd0-11e7-979a-61e803d9de65.jpg)

```html
<ul class="c-ingredients">
	<li class="c-ingredients__item">Apple</li>
	<li class="c-ingredients__item">Carrot stripes</li>
	<li class="c-ingredients__item">Papaya bits</li>
	<li class="c-ingredients__item">Pineapple chips</li>
</ul>
```

The first thing that I would consider doing would be to use the already built-in `.o-list-inline` and `.o-box` objects. 

The issue that I have is the way this is going to be implemented. What I do know is that I don't want to litter the component with object classes.( **Is this a thing with inuitcss?**).

So my approach is the following one:

```css
.c-ingredients {
	@extend .o-list-inline;
	@extend .o-box;
	@extend .o-box--small;
	background: #efefef;
	color: #484546;
}
.c-ingredients__item {
	@extend .o-list-inline__item;
	text-transform: lowercase;
	&:first-child {
	  text-transform: capitalize;
	}
	&:after {
	  content: ", ";
	}
  &:last-child:after {
    content: "";
  }
}
```
and the output:

```css
.o-box, .c-ingredients {
  display: block;
  padding: 10px;
}
.o-box--small, .c-ingredients {
  padding: 8px;
}
.o-list-inline, .c-ingredients {
  margin-left: 0;
  list-style: none;
}
.o-list-inline__item, .c-ingredients__item {
  display: inline-block;
}
.c-ingredients {
  background: #efefef;
}
.c-ingredients__item {
  text-transform: lowercase;
}
.c-ingredients__item:first-child {
  text-transform: capitalize;
}
.c-ingredients__item:after {
  content: ", ";
}
.c-ingredients__item:last-child:after {
  content: "";
}
```
Doing it this way I avoid having object classes mixed with my component thus:
1. My component is self-contained
1. My component is easily maintened
1. My component can be easily updated

The thing is that the component in question could be built in this way too:

```html
<ul class="o-list-inline o-box o-box--small c-alt-ingredients">
	<li class="o-list-inline__item c-alt-ingredients__item">Apple</li>
	<li class="o-list-inline__item c-alt-ingredients__item">Carrot stripes</li>
	<li class="o-list-inline__item c-alt-ingredients__item">Papaya bits</li>
	<li class="o-list-inline__item c-alt-ingredients__item">Pineapple chips</li>
</ul>
```
```css
.c-alt-ingredients {
	background: #efefef;
	color: #484546;
}
.c-alt-ingredients__item {
	text-transform: lowercase;
	&:first-child {
	  text-transform: capitalize;
	}
	&:after {
	  content: ", ";
	}
  &:last-child:after {
    content: "";
  }
}
```

This was proposed to me by a seasoned CSS author. He proposed this solution because I wanted the ingredient components to have different paddings at different breakpoints. This is what he came up with:

```html
<ul class="o-list-inline o-box o-box--small u-padding-large@desktop c-alt-ingredients">
	<li class="o-list-inline__item c-alt-ingredients__item">Apple</li>
	<li class="o-list-inline__item c-alt-ingredients__item">Carrot stripes</li>
	<li class="o-list-inline__item c-alt-ingredients__item">Papaya bits</li>
	<li class="o-list-inline__item c-alt-ingredients__item">Pineapple chips</li>
</ul>
```
and this is what I came up with:

```html
<ul class="c-ingredients">
	<li class="c-ingredients__item">Apple</li>
	<li class="c-ingredients__item">Carrot stripes</li>
	<li class="c-ingredients__item">Papaya bits</li>
	<li class="c-ingredients__item">Pineapple chips</li>
</ul>

<style>
.c-ingredients {
	@extend .o-list-inline;
	@extend .o-box;
	@extend .o-box--small;
	/* Larger paddings */
	@include mq($from: desktop) {
		padding: $inuit-global-spacing-unit-large;
	}
	background: #efefef;
	color: #484546;
}
.c-ingredients__item {
	@extend .o-list-inline__item;
	text-transform: lowercase;
	&:first-child {
	  text-transform: capitalize;
	}
	&:after {
	  content: ", ";
	}
  &:last-child:after {
    content: "";
  }
}
</style>
```

His argument was that if I ever wanted to position my component somewhere where I wouldn't want to have its paddings scaled I would have a problem. He was right! 

```css
	@include mq($from: desktop) {
		padding: $inuit-global-spacing-unit-large;
	}
```
^This had to go..

Now the only thing that I needed to do was to add a utility class (u-padding-large@desktop) to my component.

Finaly,

his solution:

```html
<ul class="o-list-inline o-box o-box--small u-padding-large@desktop c-alt-ingredients">
	<li class="o-list-inline__item c-alt-ingredients__item">Apple</li>
	<li class="o-list-inline__item c-alt-ingredients__item">Carrot stripes</li>
	<li class="o-list-inline__item c-alt-ingredients__item">Papaya bits</li>
	<li class="o-list-inline__item c-alt-ingredients__item">Pineapple chips</li>
</ul>
```
```css
.c-alt-ingredients {
	background: #efefef;
	color: #484546;
}
.c-alt-ingredients__item {
	text-transform: lowercase;
	&:first-child {
	  text-transform: capitalize;
	}
	&:after {
	  content: ", ";
	}
  &:last-child:after {
    content: "";
  }
}
```

my solution:

```html
<!-- basic component -->
<ul class="c-ingredients">
	<li class="c-ingredients__item">Apple</li>
	<li class="c-ingredients__item">Carrot stripes</li>
	<li class="c-ingredients__item">Papaya bits</li>
	<li class="c-ingredients__item">Pineapple chips</li>
</ul>

<!-- large paddings @desktop component -->
<ul class="c-ingredients u-padding-large@desktop">
	<li class="c-ingredients__item">Apple</li>
	<li class="c-ingredients__item">Carrot stripes</li>
	<li class="c-ingredients__item">Papaya bits</li>
	<li class="c-ingredients__item">Pineapple chips</li>
</ul>
```
```css
.c-ingredients {
	@extend .o-list-inline;
	@extend .o-box;
	@extend .o-box--small;
	background: #efefef;
	color: #484546;
}
.c-ingredients__item {
	@extend .o-list-inline__item;
	text-transform: lowercase;
	&:first-child {
	  text-transform: capitalize;
	}
	&:after {
	  content: ", ";
	}
  &:last-child:after {
    content: "";
  }
}
```
I have seen a lot of CSS authors doing the same thing and due to the fact that I very recently decided to dive into the inuitcss framework I am wondering which method is the right one. It certainly feels that my method is the preferred one. I think that ones markup should not have object classes injected in components. You can achieve the exact same result by extending the object classes to the components in the CSS. The truth is that I cannot see why the other guys solution wouldn't scale properly. Can you?
What are the problems in the long run if you write CSS like the guy that proposed me the other solution.
I keep looking at it and I cannot imagine what could break. 
**Ok.. it is not self contained.. So what??**

And one last thing.. I do not want to extend classes in my CSS. Harry wrote an [article](https://csswizardry.com/2014/01/extending-silent-classes-in-sass/) about it. Also, I vaguely remember having object classes together with silent classes. Wasn't that a thing? What changed?

**Comment by csshugs** [comment]
> I am wondering which method is the right one.

This will sound very cliché now, but IMO there really is no “right” method. This is to a large amount a matter of preference and personal taste. 

> It certainly feels that my method is the preferred one.

Well, it's _your_ preferred method, but I wouldn't generalise that. If you'd ask me, I would definitely advise **against** `@extend`. The reason for that is amongst others explained in Harrys article you referenced.

> I think that ones markup should not have object classes injected in components.

Again, that's really a (valid) subjective opinion and personal preference, which I definitely do not share myself. I'm convinced that most frontend developers tend to overlook how much time we spend inspecting and looking at markup. Thus I think the HTML should be as self-documenting as possible. Having every dependency for the element in the form of written-out CSS classes at hand, you instantly see which “ingredients” help the element look like it is. Managing this with Sass `@extend`s obscures the source of the parts that are being `@extend`ed. 

> What are the problems in the long run if you write CSS like the guy that proposed me the other solution.

Some people despise much classes in the markup. I don't, however I praise aiming at a sound amount of classes, i.e. avoid too much single-declaration utility classes. The right balance is the key and comes with experience. 

> Also, I vaguely remember having object classes together with silent classes. Wasn't that a thing? What changed?

It's just considered (potentially) harmful and doesn't really provide any real benefit that a Sass mixin could provide. 

---

I don't see any problem in defining the padding(s) via the `c-ingredients` components class, so your markup could look like this:

```html
<ul class="o-list-inline c-ingredients">
    <li class="o-list-inline__item c-ingredients__item">Apple</li>
    <li class="o-list-inline__item c-ingredients__item">Carrot stripes</li>
    <li class="o-list-inline__item c-ingredients__item">Papaya bits</li>
    <li class="o-list-inline__item c-ingredients__item">Pineapple chips</li>
</ul>
```

```scss
.c-ingredients {
  background: #efefef;
  color: #484546;
  padding: $inuit-global-spacing-unit-small;
  @include mq($from: desktop) {
    padding: $inuit-global-spacing-unit-large;
  }
}
.c-ingredients__item {
  text-transform: lowercase;
  &:first-child {
    text-transform: capitalize;
  }
  &:after {
    content: ", ";
  }
  &:last-child:after {
    content: "";
  }
}
```

* Your markup is not overloaded.
* You extract the structural styling to the list-inline object.
* You can control the varying padding via CSS.

But this is just—you guessed it—my personal preference. The only thing I strongly discourage everybody is using `@extend`. Everything else is totally up to you and not “wrong” per se.
