### ISSUE TITLE
[generic.reset] Undo normalize's font-family on buttons, inputs, ...

### ISSUE THREAD

**Issue by lhermann** [inuitcss/inuitcss#362]
Hi good folks of inuitcss.

I discovered that normalize.css does the following with buttons, inputs, ...

```css
/**
 * 1. Change the font styles in all browsers (opinionated).
 */
button,
input,
optgroup,
select,
textarea {
  font-family: sans-serif; /* 1 */
  ...
}
```

This, however, overwrites a font-family defined in `html` or `body`. Therefore I propose to add

```css
button,
input,
optgroup,
select,
textarea {
    font-family: inherit;
}
```

in `_generic.reset.scss` to "undo" this opinionated setting and inherit the font-family from `html` or `body`. I can create a PR if you are fine with it.

**Comment by nemanjaglumac** [comment]
Hi @lhermann ,
before someone from core members responds, just my quick question:

If you define those rules in Elements layer (for example `_elements.typography.scss), wouldn't it automatically override normalize.css (since it comes later on)?

**Comment by lhermann** [comment]
@nemanjaglumac `_elements.typography.scss` is exactly where I defined it, like so:
```scss
html {
    font-family: $font-primary;
    ...
}
```
[I made a little codepen](https://codepen.io/lhermann/pen/zjGqBo) to test it. Result: normalise.css does overwrite `font-family` on button, select, ... if it is defined in an `html` selector, but not if it is defined in a `*` selector.
