### ISSUE TITLE
Question: map-loop with current and next map value?

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#405]
Hi!
I am having troubles writing a plugin, where the loop uses the current map value for the "$from" attribute and the next map-value for the "$until" attr.

Usually, the mobile-first approach leads to mixins like this:
```scss
@each $bp-name, $bp-value in $mq-breakpoints {

    .u-hidden#{$breakpoint-separator}from-#{$bp-name}{
        @include mq($from: $bp-name) {
            display: none !important;
        }
    }

}
```
I personally am not a big fan of having to cancel a responsive utility again (like "u-hidden-from@mobile" and "u-show-from@desktop" or "u-margin-bottom@mobile" with "u-margin-none@tablet"). Therefore I would like to write utilities that are valid for only the one state they are intended for.
But to do that nicely with a mixin I need the extend the loop and get not only the current map-value, but also the next one:
```scss
@each $bp-name, $bp-value in $mq-breakpoints {

    .u-hidden#{$breakpoint-separator}from-#{$bp-name}{
        @include mq($from: $bp-name, $until: $bp-name+1) {
            display: none !important;
        }
    }

}
```
I have no idea how the do that, and I also have no idea how to check, if there is a next breakpoint at all. 
Does anybody of you know, if this is possible at all, and if so, probably a source, where I could read and learn about that?

Thank you!
