### ISSUE TITLE
Add module-specific variables

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#411]
Currently, the spacings in all the modules in inuitcss—especially in the objects layer—are created via the `$inuit-global-spacing-unit` variables. They are “baked into” the modules as they cannot be changed. This is fine as long as the user is okay with assigning the `$inuit-global-spacing-unit` for, e.g. the [default `.o-layout` variant](https://github.com/inuitcss/inuitcss/blob/eec9bcba5c98d495bdaf097e40c570d1d49ff2f2/objects/_objects.layout.scss#L72). However, if they need a `$inuit-global-spacing-unit-small` as gutter for the layout object, the only option is to use the `.o-layout--small` modifier additionally in the markup. But if this is actually the default, it is quite unnecessary to always put two classes to achieve the default variant.

```html
<div class="o-layout  o-layout--small">
  A default layout container
</div>
```

At least if the user needs a completely different value as layout gutter that is not based on the `$inuit-global-spacing-unit`s, there is no other option for the user to override the CSS of inuitcss’ layout object. This results in undoing CSS.

## Proposal
By extracting these spacing variables into module-specific variables and thus making them adjustable from “outside”, we can prevent such unnecessary undoing CSS and provide the user more customisability.

Lets stay at the layout object example. The partial could then look like this:

```scss
// Module variables
$inuit-layout-gutter:       $inuit-global-spacing-unit !default;
$inuit-layout-gutter-tiny:  $inuit-global-spacing-unit-tiny !default;
$inuit-layout-gutter-small: $inuit-global-spacing-unit-small !default;
$inuit-layout-gutter-large: $inuit-global-spacing-unit-large !default;
$inuit-layout-gutter-huge:  $inuit-global-spacing-unit-huge !default;

.o-layout {
  display: block;
  margin:  0;
  padding: 0;
  list-style: none;
  margin-left: -($inuit-layout-gutter);
}

  .o-layout__item {
    box-sizing: border-box;
    display: inline-block;
    vertical-align: top;
    width: 100%;
    padding-left: $inuit-layout-gutter;
  }



.o-layout--tiny {
  margin-left: -($inuit-layout-gutter-tiny);

  > .o-layout__item {
    padding-left: $inuit-layout-gutter-tiny;
  }

}

.o-layout--small {
  margin-left: -($inuit-layout-gutter-small);

  > .o-layout__item {
    padding-left: $inuit-layout-gutter-small;
  }

}

.o-layout--large {
  margin-left: -($inuit-layout-gutter-large);

  > .o-layout__item {
    padding-left: $inuit-layout-gutter-large;
  }

}

.o-layout--huge {
  margin-left: -($inuit-layout-gutter-huge);

  > .o-layout__item {
    padding-left: $inuit-layout-gutter-huge;
  }

}
```

This gives the user the full control over the spacings for every inuitcss module. By default, every standard variant of every inuitcss object assigns the `$inuit-global-spacing-unit`. This gives you consistency out of the box. But if, for whatever reason, the user needs to deviate from this, they now have the chance to use their custom values without introducing undoing CSS.

## Resilience

The neat thing about this is, that this mechanism does not introduce breaking changes, so it could be well included in the framework under a new minor release.
