### ISSUE TITLE
Are there any example websites using newer versions of inuitcss?

### ISSUE THREAD

**Issue by rmoestl** [inuitcss/inuitcss#412]
Hello!

First-time user of inuitcss here.

I use the [public repository of Harry's website](https://github.com/csswizardry/csswizardry.github.com) to learn how to use the framework. Unfortunately it's using a rather old version of inuitcss which in turn means that practical usages of some newer features are missing.

For example, I don't know how to set a custom font-size for a component (e.g., `c-page-footer`) that is wrapping `o-layout` (`$inuit-use-markup-fix` set to  `false`). Because in this case `o-layout__item` sets `font-size: 1rem;` and therefore overwrites a `font-size` set in parent `c-page-footer`.

Anyways, I don't want to pick your brain for that particular problem, but would love to know if there are other publicly available repos one could learn how to use inuitcss from.

Cheers,
Robert

**Comment by rowild** [comment]
I don't know of any repo's, and the one you mention is to my knowledge out-of-date.

But I can share, what I do in such a scenario hoping that others jump in and optimize the approach.

I could think f 2 scenarios:
- Define the font-size in the specific CSS selector chain:
```scss
.c-page-footer .o-layout__item {
   font-size: .92rem; // or 92% or whatever
}
```

- Create and use a helper class:
```scss
// A shorter name would probably be more user friendly, e.g.: `.u-fs-m`
.u-font-size--medium {
   font-size: 92% !important;
}
``` 
```html
<div class="c-spage-footer">
   <div class="o-layout">
      <div class="o-layout__item u-font-size--medium">
        [...]
      </div>
   </div>
</div>
```
Does this help a bit?
