### ISSUE TITLE
Provide mixins for list-bare and list-inline

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#419]
More often than using the actual `.o-list-bare` and `.o-list-inline` objects, I create mixins for those abstractions, so I can use these on my custom components. E.g.:

```scss
// _tools.list-inline.scss
@mixin list-inline() {
  display: flex;
  margin-left: 0;
  list-style: none;
}



// _components.site-nav.scss
.c-site-nav {
  @include list-inline;
  ...
}

  .c-site-nav__item {
    margin-right: 12px;
    ...
  }
```

This way, I can keep my markup “clean”, i.e. not mixing object and component classes.

## Proposal

By extracting the CSS of the list-bare and list-inline to mixins, we can give users the possibility to use just the mixins in their custom components. Additionally, we still provide the objects for those users who are more attracted towards adding the object classes to their markup.

This is backwards compatible and doesn’t introduce a breaking change, hence can be implemented into the current v6 major version.
