### ISSUE TITLE
[objects.layout] / [generic.box-sizing] Bulletproof box-sizing integration

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#89]
@inuitcss/core 

The layout object needs `box-sizing: border-box` to work properly. Without it, the layout will break.

So, when a user (for whatever reason) does not include `generic.box-sizing`, the layout will break. 

The MVP solution would be to just put `box-sizing: border-box;` to `.o-layout__item` in `objects.layout`:
```scss
/**
 * 1. Allows us to manipulate grids vertically, with text-level properties,
 *    etc.
 * 2. Default item alignment is with the tops of each other, like most
 *    traditional grid/layout systems.
 * 3. By default, all layout items are full-width (mobile first).
 * 4. Gutters provided by left padding:
 *    http://csswizardry.com/2011/08/building-better-grid-systems/
 * 5. Required to combine fluid widths and fixed gutters.
 */
.o-layout__item {
  display: inline-block; /* [1] */
  vertical-align: top; /* [2] */
  width: 100%; /* [3] */
  padding-left: $inuit-global-spacing-unit; /* [4] */
  box-sizing: border-box; /* [5] */

  @if ($inuit-use-markup-fix == false) {
    @if ($inuit-oldIE == true) {
      font-size: $inuit-global-font-size;
    }
    font-size: 1rem;
  }

}
```

This would be bulletproof for users not importing `generic.box-sizing`. 

However, for everyone else doing it the proper way and importing `generic.box-sizing`, that one line above in `.o-layout__item` is **redundant and thus waste in the compiled CSS**. 

Hence the alternative solution would be to handle it the way we used to in the pre-alpha version. I.e. [set a Sass variable to true at the end of `generic.box-sizing`](https://github.com/inuitcss/generic.box-sizing/blob/master/_generic.box-sizing.scss#L29-L31), so when this file is imported, the variable is true:
```scss
// If we have included this file, set a variable to tell the rest of the
// framework that global `box-sizing: border-box` has been set.
$inuit-global-border-box: true;
```

In `objects.layout`, [we set this exact variable to false](https://github.com/inuitcss/objects.layout/blob/master/_objects.layout.scss#L37-L40) with a `!default` flag, so when `generic.box-sizing` is **not** imported, this variable keeps false and does not get overridden beforehand in `generic.box-sizing`:
```scss
// Here we set a variable assuming that `box-sizing: border-box;` is not set
// globally. If it has been previously been defined, the following variable will
// be overriden and will be set to `true`.
$inuit-global-border-box: false !default;
```

For `o-layout__item` we [wrap the box-sizing declaration in the false varaible](https://github.com/inuitcss/objects.layout/blob/master/_objects.layout.scss#L71-L73), so that it only gets compiled, when `generic.box-sizing` is **not** imported:
```scss
/**
 * 1. Allows us to manipulate grids vertically, with text-level properties,
 *    etc.
 * 2. Default item alignment is with the tops of each other, like most
 *    traditional grid/layout systems.
 * 3. By default, all layout items are full-width (mobile first).
 * 4. Gutters provided by left padding:
 *    http://csswizardry.com/2011/08/building-better-grid-systems/
 * 5. Required to combine fluid widths and fixed gutters.
 */
.o-layout__item {
  display: inline-block; /* [1] */
  vertical-align: top; /* [2] */
  width: 100%; /* [3] */
  padding-left: $inuit-global-spacing-unit; /* [4] */

  @if $inuit-global-border-box == false {
    box-sizing: border-box; /* [5] */
  }

  @if ($inuit-use-markup-fix == false) {
    @if ($inuit-oldIE == true) {
      font-size: $inuit-global-font-size;
    }
    font-size: 1rem;
  }

}
```

The only question here is: Is this all too complex just to save one line of compiled CSS?
