### ISSUE TITLE
[objects.lint-inline] Why limit whitespace hack just for modifier?

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#94]
Why is the font-size whitespace hack [limited to the `.o-list-inline--delimited` modifier](https://github.com/inuitcss/inuitcss/blob/develop/objects/_objects.list-inline.scss#L34-L41)?

Doesn't it make sense to always strip the whitespace. e.g.:

```scss
.o-list-inline {
  margin-left: 0;
  list-style: none;
  font-size: 0;
}


  .o-list-inline__item {
    display: inline-block;
    
    @if ($inuit-oldIE == true) {
      font-size: $inuit-global-font-size;
    }
    font-size: 1rem;

  }
```

instead restricting it to the modifier? Or did I miss the initial intention behind that?
